export enum LostReasons {
  BadProspect = 1,
  Duplicate = 2,
  EnglishSpeaker = 3,
  IncompleteDetails = 4,
  LostForOtherReason = 5,
  NoAnswer = 6,
  NoInterested = 7,
  NoLongerCarShopping = 8,
  NoLongerWantsToDoBusinessWithUsPermanentlyLost = 9,
  NoQualify = 10,
  OutOfRange = 11,
  ProspectRequestedCompleteDNC = 12,
  Referral = 13,
  RTS = 14,
  SalesInteractionInADeal = 15,
  SoldUnderDiferentName = 16,
  Spam = 17,
  TransferToAnotherLocation = 18,
  ManualDeleted = 19,
}
