version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_flow
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psswd123
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
