-- AlterTable
ALTER TABLE "Credit_app_address" ADD COLUMN     "current_city" TEXT,
ADD COLUMN     "current_county" TEXT,
ADD COLUMN     "current_state" TEXT,
ADD COLUMN     "current_state_id" TEXT,
ADD COLUMN     "current_street" TEXT,
ADD COLUMN     "current_zip" TEXT,
ADD COLUMN     "mailing_city" TEXT,
ADD COLUMN     "mailing_county" TEXT,
ADD COLUMN     "mailing_state" TEXT,
ADD COLUMN     "mailing_state_id" TEXT,
ADD COLUMN     "mailing_street" TEXT,
ADD COLUMN     "mailing_zip" TEXT,
ADD COLUMN     "prev_city" TEXT,
ADD COLUMN     "prev_county" TEXT,
ADD COLUMN     "prev_state" TEXT,
ADD COLUMN     "prev_state_id" TEXT,
ADD COLUMN     "prev_street" TEXT,
ADD COLUMN     "prev_zip" TEXT;
