export enum LeadHistoryCategoriesEnum {
  AddNote = 1,
  AppointmentSchedule = 2,
  SpokeToProspect = 3,
  LeftMessage = 4,
  NoAnswer = 5,
  BadPhoneNumber = 6,
  ManualSMSSent = 7,
  ManualEmailSent = 8,
  ReceivedSMSFromProspect = 9,
  ReceivedEmailFromProspect = 10,
  ProspectVisitedDelearship = 11,
  ProspectTestDroveVehicleDemo = 12,
  DealInProgress = 13,
  Sold = 14,
  MarkAsLost = 15,
  ProspectRequestedDNC = 16,
  AddTask = 17,
  SetStatus = 18,
  DeliveryScheduled = 19,
  Deposit = 20,
  RemovedNotification = 21, // (conversation)
}

export const CategoriesEnumToString: Record<LeadHistoryCategoriesEnum, string> = {
  [LeadHistoryCategoriesEnum.AddNote]: 'Add note',
  [LeadHistoryCategoriesEnum.AppointmentSchedule]: 'Appointment Schedule',
  [LeadHistoryCategoriesEnum.SpokeToProspect]: 'Spoke to Prospect',
  [LeadHistoryCategoriesEnum.LeftMessage]: 'Left Message',
  [LeadHistoryCategoriesEnum.NoAnswer]: 'No Answer',
  [LeadHistoryCategoriesEnum.BadPhoneNumber]: 'Bad Phone Number',
  [LeadHistoryCategoriesEnum.ManualSMSSent]: 'Manual SMS Sent',
  [LeadHistoryCategoriesEnum.ManualEmailSent]: 'Manual Email Sent',
  [LeadHistoryCategoriesEnum.RemovedNotification]: 'Removed Notification',
  [LeadHistoryCategoriesEnum.ReceivedSMSFromProspect]: 'Received SMS from Prospect',
  [LeadHistoryCategoriesEnum.ReceivedEmailFromProspect]: 'Received Email from Prospect',
  [LeadHistoryCategoriesEnum.ProspectVisitedDelearship]: 'Prospect Visited Delearship',
  [LeadHistoryCategoriesEnum.ProspectTestDroveVehicleDemo]: 'Prospect Test Drove Vehicle/Demo',
  [LeadHistoryCategoriesEnum.DealInProgress]: 'Deal in Progress',
  [LeadHistoryCategoriesEnum.Sold]: 'Sold',
  [LeadHistoryCategoriesEnum.MarkAsLost]: 'Mark as Lost',
  [LeadHistoryCategoriesEnum.ProspectRequestedDNC]: 'Prospect Requested DNC',
  [LeadHistoryCategoriesEnum.AddTask]: 'Add a Task',
  [LeadHistoryCategoriesEnum.SetStatus]: 'Set Status',
  [LeadHistoryCategoriesEnum.DeliveryScheduled]: 'Delivery Scheduled',
  [LeadHistoryCategoriesEnum.Deposit]: 'Deposit',
};

export const subcategoryToGroupMap: Record<number, string> = {
  [LeadHistoryCategoriesEnum.AddNote]: 'Note',
  [LeadHistoryCategoriesEnum.AddTask]: 'Note',
  [LeadHistoryCategoriesEnum.SpokeToProspect]: 'Call',
  [LeadHistoryCategoriesEnum.NoAnswer]: 'Call',
  [LeadHistoryCategoriesEnum.LeftMessage]: 'Call',
  [LeadHistoryCategoriesEnum.ManualSMSSent]: 'SMS',
  [LeadHistoryCategoriesEnum.RemovedNotification]: 'SMS',
  [LeadHistoryCategoriesEnum.ReceivedSMSFromProspect]: 'SMS',
  [LeadHistoryCategoriesEnum.ProspectVisitedDelearship]: 'Appointment',
  [LeadHistoryCategoriesEnum.AppointmentSchedule]: 'Appointment',
  [LeadHistoryCategoriesEnum.ManualEmailSent]: 'Email',
  [LeadHistoryCategoriesEnum.ReceivedEmailFromProspect]: 'Email',
  [LeadHistoryCategoriesEnum.DealInProgress]: 'Deal',
  [LeadHistoryCategoriesEnum.MarkAsLost]: 'Lost',
  [LeadHistoryCategoriesEnum.BadPhoneNumber]: 'Lost',
  [LeadHistoryCategoriesEnum.DeliveryScheduled]: 'Sold',
  [LeadHistoryCategoriesEnum.Sold]: 'Sold',
  [LeadHistoryCategoriesEnum.Deposit]: 'Sold',
  [LeadHistoryCategoriesEnum.ProspectRequestedDNC]: 'Other',
  [LeadHistoryCategoriesEnum.SetStatus]: 'Other',
  [LeadHistoryCategoriesEnum.ProspectTestDroveVehicleDemo]: 'Other',
};
